version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow_net

  webserver:
    build: .
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__SMTP__SMTP_HOST=mailhog
      - AIRFLOW__SMTP__SMTP_PORT=1025
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflow@example.com
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow.cfg:/opt/airflow/airflow.cfg
    networks:
      - airflow_net

  scheduler:
    build: .
    depends_on:
      - webserver
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow.cfg:/opt/airflow/airflow.cfg
    networks:
      - airflow_net

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - airflow_net

volumes:
  postgres-db-volume:

networks:
  airflow_net:
